services:
  - type: web
    name: heatpath-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: ORS_API_KEY
        sync: false
      - key: WAQI_TOKEN
        sync: false
      - key: ENV
        value: production